services:
  postgres:
    image: postgres:15-alpine
    container_name: cms_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cms_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cms_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - cms_network

volumes:
  postgres_data:

networks:
  cms_network:
    driver: bridge
