export const ErrorCodes = {
  // ── Auth ────────────────────────────────────────────────────
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',

  // ── Resources ───────────────────────────────────────────────
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  MENU_ITEM_NOT_FOUND: 'MENU_ITEM_NOT_FOUND',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_FILE_NOT_FOUND: 'MEDIA_FILE_NOT_FOUND',
  LANGUAGE_NOT_FOUND: 'LANGUAGE_NOT_FOUND',
  BLOCK_TYPE_NOT_FOUND: 'BLOCK_TYPE_NOT_FOUND',
  PAGE_TEMPLATE_NOT_FOUND: 'PAGE_TEMPLATE_NOT_FOUND',
  SETTINGS_NOT_FOUND: 'SETTINGS_NOT_FOUND',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

  // ── Conflicts ───────────────────────────────────────────────
  POST_DUPLICATE: 'POST_DUPLICATE',
  PAGE_TEMPLATE_DUPLICATE: 'PAGE_TEMPLATE_DUPLICATE',
  MENU_DUPLICATE: 'MENU_DUPLICATE',
  LANGUAGE_DUPLICATE: 'LANGUAGE_DUPLICATE',
  BLOCK_TYPE_DUPLICATE: 'BLOCK_TYPE_DUPLICATE',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',

  // ── Validation ──────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_SCHEMA: 'INVALID_SCHEMA',
  INVALID_BULK_ACTION: 'INVALID_BULK_ACTION',
  INVALID_FILE: 'INVALID_FILE',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  VALUE_TOO_LONG: 'VALUE_TOO_LONG',
  RELATION_VIOLATION: 'RELATION_VIOLATION',

  // ── System ──────────────────────────────────────────────────
  DB_TIMEOUT: 'DB_TIMEOUT',
  DB_TRANSACTION_CONFLICT: 'DB_TRANSACTION_CONFLICT',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
